# Generated by Django 3.0.4 on 2020-03-21 19:57

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200321_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman')], default=accounts.models.Gender['Man'], max_length=10),
        ),
    ]
