# Generated by Django 3.0.4 on 2020-03-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_participant_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
