# Generated by Django 3.0.4 on 2020-03-22 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_participant_is_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_id', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('authority', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('request_datetime', models.DateTimeField(auto_now_add=True)),
                ('verify_datetime', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='accounts.Participant')),
            ],
        ),
    ]
