# Generated by Django 3.0.4 on 2020-03-23 06:47

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('accounts', '0007_auto_20200322_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.AlterModelTable(
            name='member',
            table='auth_user',
        ),
    ]
