# Generated by Django 3.0.4 on 2020-03-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200323_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_document_verified',
            field=models.BooleanField(default=False),
        ),
    ]
