# Generated by Django 3.0.4 on 2020-03-23 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kabaramadalapeste', '0008_challenge_challenge_id'),
        ('accounts', '0008_auto_20200323_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='currently_at_island',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_participants', to='kabaramadalapeste.Island'),
        ),
    ]
