# Generated by Django 3.0.4 on 2020-03-23 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_participant_currently_at_island'),
        ('accounts', '0009_auto_20200323_2007'),
    ]

    operations = [
    ]
