# Generated by Django 3.0.4 on 2020-03-24 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200323_2007'),
        ('accounts', '0009_participant_is_document_verified'),
    ]

    operations = [
    ]
