# Generated by Django 3.0.4 on 2020-03-25 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200324_1853'),
        ('accounts', '0010_merge_20200323_2026'),
    ]

    operations = [
    ]
