# Generated by Django 3.0.4 on 2020-03-26 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20200325_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('success', 'success'), ('info', 'info'), ('warning', 'warning'), ('error', 'error')], default='info', max_length=20)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent')], default='Draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('send_to_all', models.BooleanField(default=False)),
                ('recipients', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notification_datas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
