# Generated by Django 3.0.4 on 2020-03-26 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_notificationdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationdata',
            old_name='send_to_all',
            new_name='send_to_all_participants',
        ),
        migrations.AlterField(
            model_name='notificationdata',
            name='recipients',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
