# Generated by Django 3.0.4 on 2020-03-28 21:16

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200327_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='picture'),
        ),
    ]
