# Generated by Django 3.0.4 on 2020-03-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_participant_stat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='stat_image_with_background',
            field=models.ImageField(default='stats-back/base_stat_back.png', null=True, upload_to='stats-back/'),
        ),
    ]
