# Generated by Django 3.0.4 on 2020-09-09 11:12

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200909_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='picture',
        ),
        migrations.AddField(
            model_name='team',
            name='picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='picture/user_default.png', upload_to='picture'),
        ),
    ]
