# Generated by Django 3.0.4 on 2023-08-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20200909_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='chat_room_link',
            field=models.URLField(default=None),
        ),
    ]
