# Generated by Django 3.0.4 on 2023-08-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_team_chat_room_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='chat_room_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
