# Generated by Django 3.0.4 on 2020-03-19 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_judgeable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShortAnswerQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('question', models.FileField(upload_to='soals/')),
                ('correct_answer', models.CharField(max_length=50)),
                ('answer_type', models.CharField(choices=[('INT', 'int'), ('FLT', 'float'), ('STR', 'string')], default='STR', max_length=3)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortanswerquestion', to='kabaramadalapeste.Challenge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JudgeableQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('question', models.FileField(upload_to='soals/')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgeablequestion', to='kabaramadalapeste.Challenge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('island_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kabaramadalapeste.Challenge')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeRewardItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('SK', 'sekke'), ('K1', 'key 1'), ('K2', 'key 2'), ('K3', 'key 3')], default='SK', max_length=2)),
                ('amount', models.IntegerField(default=0)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='kabaramadalapeste.Challenge')),
            ],
            options={
                'unique_together': {('challenge', 'reward_type')},
            },
        ),
    ]
