# Generated by Django 3.0.4 on 2020-03-21 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kabaramadalapeste', '0002_treasure_treasurekeyitem_treasurerewarditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Way',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_ends', to='kabaramadalapeste.Island')),
                ('second_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_ends', to='kabaramadalapeste.Island')),
            ],
        ),
    ]
