# Generated by Django 3.0.4 on 2020-03-21 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200321_1946'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('kabaramadalapeste', '0004_auto_20200321_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurerewarditem',
            name='reward_type',
            field=models.CharField(choices=[('SK', 'sekke'), ('K1', 'key 1'), ('K2', 'key 2'), ('K3', 'key 3'), ('VIS', 'vision'), ('TXP', 'travel express'), ('CHP', 'challenge plus'), ('PRC', 'prophecy'), ('BLY', 'bully')], default='SK', max_length=3),
        ),
        migrations.CreateModel(
            name='ParticipantIslandStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did_anchor', models.BooleanField(default=False)),
                ('challenge_accepted', models.BooleanField(default=False)),
                ('question_object_id', models.PositiveIntegerField()),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kabaramadalapeste.Island')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Participant')),
                ('question_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('treasure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kabaramadalapeste.Treasure')),
            ],
            options={
                'unique_together': {('participant', 'island')},
            },
        ),
    ]
