# Generated by Django 3.0.4 on 2020-03-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabaramadalapeste', '0005_auto_20200321_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantislandstatus',
            old_name='challenge_accepted',
            new_name='did_accept_challenge',
        ),
        migrations.AddField(
            model_name='participantislandstatus',
            name='anchored_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='participantislandstatus',
            name='challenge_accepted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='participantislandstatus',
            name='did_open_treasure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participantislandstatus',
            name='did_reached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participantislandstatus',
            name='reached_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='participantislandstatus',
            name='treasure_opened_at',
            field=models.DateTimeField(null=True),
        ),
    ]
