# Generated by Django 3.0.4 on 2020-03-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kabaramadalapeste', '0006_auto_20200321_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantislandstatus',
            old_name='did_reached',
            new_name='did_reach',
        ),
    ]
