# Generated by Django 3.0.4 on 2020-03-21 20:38

from django.db import migrations, models


def set_my_defaults(apps, schema_editor):
    Challenge = apps.get_model('kabaramadalapeste', 'Challenge')
    for challenge in Challenge.objects.all().iterator():
        challenge.challenge_id = challenge.id
        challenge.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kabaramadalapeste', '0007_auto_20200321_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenge_id',
            field=models.PositiveIntegerField(default=0, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(set_my_defaults, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
