# Generated by Django 3.0.4 on 2020-03-23 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200321_1946'),
        ('kabaramadalapeste', '0008_challenge_challenge_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantPropertyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('SK', 'sekke'), ('K1', 'key 1'), ('K2', 'key 2'), ('K3', 'key 3'), ('VIS', 'vision'), ('TXP', 'travel express'), ('CHP', 'challenge plus'), ('PRC', 'prophecy'), ('BLY', 'bully')], default='SK', max_length=3)),
                ('amount', models.IntegerField(default=0)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='accounts.Participant')),
            ],
            options={
                'unique_together': {('participant', 'property_type')},
            },
        ),
    ]
