# Generated by Django 3.0.4 on 2020-03-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabaramadalapeste', '0009_participantpropertyitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantislandstatus',
            name='question_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
