# Generated by Django 3.0.4 on 2020-03-23 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kabaramadalapeste', '0010_auto_20200323_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantislandstatus',
            name='question_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
