# Generated by Django 3.0.4 on 2020-03-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabaramadalapeste', '0011_auto_20200323_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantislandstatus',
            old_name='did_anchor',
            new_name='currently_anchored',
        ),
        migrations.RenameField(
            model_name='participantislandstatus',
            old_name='anchored_at',
            new_name='last_anchored_at',
        ),
        migrations.AddField(
            model_name='participantislandstatus',
            name='currently_in',
            field=models.BooleanField(default=False),
        ),
    ]
