# Generated by Django 3.0.4 on 2020-03-25 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20200323_2026'),
        ('kabaramadalapeste', '0012_auto_20200324_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OD', 'deleted'), ('OA', 'accepted'), ('OC', 'active')], default='OC', max_length=2)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('close_datetime', models.DateTimeField(blank=True, null=True)),
                ('accepted_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_trade_offers', to='accounts.Participant')),
                ('creator_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_trade_offers', to='accounts.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='TradeOfferSuggestedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('SK', 'sekke'), ('K1', 'key 1'), ('K2', 'key 2'), ('K3', 'key 3'), ('VIS', 'vision'), ('TXP', 'travel express'), ('CHP', 'challenge plus'), ('PRC', 'prophecy'), ('BLY', 'bully')], default='SK', max_length=3)),
                ('amount', models.IntegerField(default=0)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_items', to='kabaramadalapeste.TradeOffer')),
            ],
            options={
                'unique_together': {('offer', 'property_type')},
            },
        ),
        migrations.CreateModel(
            name='TradeOfferRequestedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('SK', 'sekke'), ('K1', 'key 1'), ('K2', 'key 2'), ('K3', 'key 3'), ('VIS', 'vision'), ('TXP', 'travel express'), ('CHP', 'challenge plus'), ('PRC', 'prophecy'), ('BLY', 'bully')], default='SK', max_length=3)),
                ('amount', models.IntegerField(default=0)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_items', to='kabaramadalapeste.TradeOffer')),
            ],
            options={
                'unique_together': {('offer', 'property_type')},
            },
        ),
    ]
