# Generated by Django 3.0.4 on 2020-03-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabaramadalapeste', '0013_tradeoffer_tradeofferrequesteditem_tradeoffersuggesteditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantislandstatus',
            name='is_treasure_visible',
            field=models.BooleanField(default=False),
        ),
    ]
