# Generated by Django 3.0.4 on 2020-03-25 13:35

from django.db import migrations, models
import kabaramadalapeste.models


class Migration(migrations.Migration):

    dependencies = [
        ('kabaramadalapeste', '0015_auto_20200325_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgeablesubmit',
            name='submit_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Correct', 'Correct'), ('Wrong', 'Wrong')], default=kabaramadalapeste.models.BaseSubmit.SubmitStatus['Pending'], max_length=20),
        ),
        migrations.AlterField(
            model_name='shortanswersubmit',
            name='submit_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Correct', 'Correct'), ('Wrong', 'Wrong')], default=kabaramadalapeste.models.BaseSubmit.SubmitStatus['Pending'], max_length=20),
        ),
    ]
