# Generated by Django 3.0.4 on 2020-03-25 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20200325_0642'),
        ('kabaramadalapeste', '0016_auto_20200325_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('ability_type', models.CharField(choices=[('VIS', 'vision'), ('TXP', 'travel express'), ('CHP', 'challenge plus'), ('PRC', 'prophecy'), ('BLY', 'bully')], default='VIS', max_length=3)),
                ('is_active', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_abilities', to='accounts.Participant')),
            ],
        ),
    ]
