# Generated by Django 3.0.4 on 2020-03-26 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kabaramadalapeste', '0017_auto_20200325_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgeablesubmit',
            name='judged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
