# Generated by Django 3.0.4 on 2020-03-26 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kabaramadalapeste', '0017_abilityusage'),
        ('kabaramadalapeste', '0017_auto_20200325_2336'),
    ]

    operations = [
    ]
