# Generated by Django 3.0.4 on 2020-03-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kabaramadalapeste', '0018_judgeablesubmit_judged_by'),
        ('kabaramadalapeste', '0018_merge_20200326_1216'),
    ]

    operations = [
    ]
