# Generated by Django 3.0.4 on 2020-03-26 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20200325_0642'),
        ('kabaramadalapeste', '0019_merge_20200326_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='peste_guidance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Peste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_found', models.BooleanField(default=False)),
                ('found_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Participant')),
                ('island', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kabaramadalapeste.Island')),
            ],
        ),
    ]
