# Generated by Django 3.0.4 on 2020-03-26 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20200325_0642'),
        ('kabaramadalapeste', '0019_merge_20200326_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandargahConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_possible_invest', models.IntegerField(default=3000)),
                ('max_possible_invest', models.IntegerField(default=4000)),
                ('profit_coefficient', models.FloatField(default=1.5)),
                ('loss_coefficient', models.FloatField(default=0.5)),
                ('min_interval_investments', models.IntegerField(default=30000)),
                ('max_interval_investments', models.IntegerField(default=42000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BandargahInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='accounts.Participant')),
            ],
        ),
    ]
