# Generated by Django 3.0.4 on 2020-03-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabaramadalapeste', '0020_bandargahconfiguration_bandargahinvestment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandargahinvestment',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
