# Generated by Django 3.0.4 on 2020-03-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kabaramadalapeste', '0021_auto_20200326_1730'),
        ('kabaramadalapeste', '0021_bandargahinvestment_is_applied'),
    ]

    operations = [
    ]
