# Generated by Django 3.0.4 on 2020-03-26 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20200325_0642'),
        ('kabaramadalapeste', '0022_merge_20200326_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bully',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('expired_datetime', models.DateTimeField(blank=True, null=True)),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullies', to='kabaramadalapeste.Island')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullies', to='accounts.Participant')),
            ],
        ),
    ]
