# Generated by Django 3.0.4 on 2020-03-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabaramadalapeste', '0025_auto_20200327_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesteconfiguration',
            name='island_spade_cost',
            field=models.IntegerField(default=12000),
        ),
    ]
