# Generated by Django 3.0.4 on 2020-03-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabaramadalapeste', '0026_auto_20200327_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesteconfiguration',
            name='peste_reward',
            field=models.IntegerField(default=24000),
        ),
    ]
