# Generated by Django 3.0.4 on 2020-03-28 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kabaramadalapeste', '0026_pesteconfiguration_is_peste_available'),
        ('kabaramadalapeste', '0027_auto_20200327_2318'),
    ]

    operations = [
    ]
