# Generated by Django 3.0.4 on 2020-03-29 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0016_auto_20200327_0006'),
        ('kabaramadalapeste', '0028_merge_20200328_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('Nope', 'Nope'), ('Set start', 'Setstart'), ('Move', 'Move'), ('Anchor', 'Anchor'), ('Open treasure', 'Opentreasure'), ('Spade', 'Spade'), ('Accept challenge', 'Acceptchallenge'), ('Create offer', 'Createoffer'), ('Delete offer', 'Deleteoffer'), ('Accept offer', 'Acceptoffer'), ('Use ability', 'Useability'), ('Invest', 'Invest'), ('Submit', 'Submit')], default='Nope', max_length=20)),
                ('related_object_id', models.PositiveIntegerField(null=True)),
                ('related_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('where', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='kabaramadalapeste.Island')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='accounts.Participant')),
            ],
        ),
    ]
