# Generated by Django 3.0.4 on 2020-03-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabaramadalapeste', '0030_auto_20200329_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameeventlog',
            name='event_type',
            field=models.CharField(choices=[('Nope', 'Nope'), ('Set start', 'Setstart'), ('Move', 'Move'), ('Anchor', 'Anchor'), ('Open treasure', 'Opentreasure'), ('Spade', 'Spade'), ('Accept challenge', 'Acceptchallenge'), ('Create offer', 'Createoffer'), ('Delete offer', 'Deleteoffer'), ('Accept offer', 'Acceptoffer'), ('Use ability', 'Useability'), ('Invest', 'Invest'), ('Submit', 'Submit'), ('Bully target', 'Bullytarget')], default='Nope', max_length=20),
        ),
    ]
