# Generated by Django 3.0.4 on 2020-04-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabaramadalapeste', '0031_auto_20200329_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantpropertyitem',
            name='property_type',
            field=models.CharField(choices=[('SK', 'sekke'), ('K1', 'key 1'), ('K2', 'key 2'), ('K3', 'key 3')], default='SK', max_length=3),
        ),
        migrations.AlterField(
            model_name='tradeofferrequesteditem',
            name='property_type',
            field=models.CharField(choices=[('SK', 'sekke'), ('K1', 'key 1'), ('K2', 'key 2'), ('K3', 'key 3')], default='SK', max_length=3),
        ),
        migrations.AlterField(
            model_name='tradeoffersuggesteditem',
            name='property_type',
            field=models.CharField(choices=[('SK', 'sekke'), ('K1', 'key 1'), ('K2', 'key 2'), ('K3', 'key 3')], default='SK', max_length=3),
        ),
        migrations.AlterField(
            model_name='treasurerewarditem',
            name='reward_type',
            field=models.CharField(choices=[('SK', 'sekke'), ('K1', 'key 1'), ('K2', 'key 2'), ('K3', 'key 3')], default='SK', max_length=3),
        ),
    ]
