# Generated by Django 3.0.4 on 2020-04-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabaramadalapeste', '0032_auto_20200424_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameeventlog',
            name='event_type',
            field=models.CharField(choices=[('Nope', 'Nope'), ('Set start', 'Setstart'), ('Move', 'Move'), ('Anchor', 'Anchor'), ('Open treasure', 'Opentreasure'), ('Spade', 'Spade'), ('Find peste', 'Findpeste'), ('Accept challenge', 'Acceptchallenge'), ('Create offer', 'Createoffer'), ('Delete offer', 'Deleteoffer'), ('Accept offer', 'Acceptoffer'), ('Use ability', 'Useability'), ('Invest', 'Invest'), ('Submit', 'Submit'), ('Judge correct', 'Judgecorrect'), ('Judge wrong', 'Judgewrong'), ('Bully target', 'Bullytarget')], default='Nope', max_length=20),
        ),
    ]
