# Generated by Django 3.0.4 on 2020-03-16 06:59

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('team_type', models.CharField(choices=[('فنی', 'Technical'), ('علمی', 'Scientific'), ('رسانه', 'Media')], default=homepage.models.TeamType['Technical'], max_length=10)),
                ('profile_picture', models.ImageField(default='profiles/john_doe.jpeg', upload_to='profiles/')),
            ],
        ),
    ]
