# Generated by Django 3.0.4 on 2020-03-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
