# Generated by Django 3.0.4 on 2020-03-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_siteconfiguration_is_signup_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='island_spaid_cost',
            field=models.IntegerField(default=15000),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='peste_reward',
            field=models.IntegerField(default=30000),
        ),
    ]
