# Generated by Django 3.0.4 on 2020-03-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200326_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='island_spaid_cost',
            new_name='island_spade_cost',
        ),
    ]
