# Generated by Django 3.0.4 on 2020-03-27 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20200326_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='island_spade_cost',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='peste_reward',
        ),
    ]
