# Generated by Django 3.0.4 on 2020-03-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20200327_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='is_game_running',
            field=models.BooleanField(default=False),
        ),
    ]
