# Generated by Django 3.0.4 on 2020-03-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_siteconfiguration_is_game_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='upload_stats_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
