# Generated by Django 3.0.4 on 2020-03-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_siteconfiguration_upload_stats_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='is_game_over',
            field=models.BooleanField(default=False),
        ),
    ]
