# Generated by Django 3.0.4 on 2020-04-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_siteconfiguration_is_game_over'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='upload_stats_enabled',
        ),
    ]
